apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lantz-jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: student-6
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: https://github.com/farthinder/argocd-katas-training
      targetRevision: main
      ref: values
